export const  InternationalMatches = {
    matchType: "International",
    seriesMatches: [
      {
        seriesAdWrapper: {
          seriesId: 7534,
          seriesName: "Sri Lanka tour of Bangladesh, 2024",
          matches: [
            {
              matchInfo: {
                matchId: 88963,
                seriesId: 7534,
                seriesName: "Sri Lanka tour of Bangladesh, 2024",
                matchDesc: "2nd Test",
                matchFormat: "TEST",
                startDate: "1711771200000",
                endDate: "1712142000000",
                state: "Complete",
                status: "Sri Lanka won by 192 runs",
                team1: {
                  teamId: 5,
                  teamName: "Sri Lanka",
                  teamSName: "SL",
                  imageId: 172119,
                },
                team2: {
                  teamId: 6,
                  teamName: "Bangladesh",
                  teamSName: "BAN",
                  imageId: 172120,
                },
                venueInfo: {
                  id: 93,
                  ground: "Zahur Ahmed Chowdhury Stadium",
                  city: "Chattogram",
                  timezone: "+06:00",
                  latitude: "22.355898",
                  longitude: "91.767766",
                },
                currBatTeamId: 5,
                seriesStartDt: "1709510400000",
                seriesEndDt: "1712275200000",
                isTimeAnnounced: true,
                stateTitle: "SL Won",
              },
              matchScore: {
                team1Score: {
                  inngs1: {
                    inningsId: 1,
                    runs: 531,
                    wickets: 10,
                    overs: 158.6,
                  },
                  inngs2: {
                    inningsId: 3,
                    runs: 157,
                    wickets: 7,
                    overs: 39.6,
                    isDeclared: true,
                  },
                },
                team2Score: {
                  inngs1: {
                    inningsId: 2,
                    runs: 178,
                    wickets: 10,
                    overs: 68.4,
                  },
                  inngs2: {
                    inningsId: 4,
                    runs: 318,
                    wickets: 10,
                    overs: 84.6,
                  },
                },
              },
            },
          ],
        },
      },
      {
        adDetail: {
          name: "native_matches",
          layout: "native_large",
          position: 1,
        },
      },
      {
        seriesAdWrapper: {
          seriesId: 7727,
          seriesName: "Namibia tour of Oman, 2024",
          matches: [
            {
              matchInfo: {
                matchId: 91337,
                seriesId: 7727,
                seriesName: "Namibia tour of Oman, 2024",
                matchDesc: "4th T20I",
                matchFormat: "T20",
                startDate: "1712313000000",
                endDate: "1712325600000",
                state: "Complete",
                status: "Namibia won by 24 runs",
                team1: {
                  teamId: 161,
                  teamName: "Namibia",
                  teamSName: "NAM",
                  imageId: 172229,
                },
                team2: {
                  teamId: 304,
                  teamName: "Oman",
                  teamSName: "OMAN",
                  imageId: 172353,
                },
                venueInfo: {
                  id: 549,
                  ground: "Al Amerat Cricket Ground (Ministry Turf 1)",
                  city: "Al Amerat",
                  timezone: "+04:00",
                  latitude: "23.483316",
                  longitude: "58.4589062",
                },
                currBatTeamId: 161,
                seriesStartDt: "1711929600000",
                seriesEndDt: "1712620800000",
                isTimeAnnounced: true,
                stateTitle: "NAM Won",
              },
              matchScore: {
                team1Score: {
                  inngs1: {
                    inningsId: 1,
                    runs: 164,
                    wickets: 4,
                    overs: 19.6,
                  },
                },
                team2Score: {
                  inngs1: {
                    inningsId: 2,
                    runs: 140,
                    wickets: 9,
                    overs: 19.6,
                  },
                },
              },
            },
            {
              matchInfo: {
                matchId: 91328,
                seriesId: 7727,
                seriesName: "Namibia tour of Oman, 2024",
                matchDesc: "3rd T20I",
                matchFormat: "T20",
                startDate: "1712226600000",
                endDate: "1712239200000",
                state: "Complete",
                status: "Oman won by 8 wkts",
                team1: {
                  teamId: 161,
                  teamName: "Namibia",
                  teamSName: "NAM",
                  imageId: 172229,
                },
                team2: {
                  teamId: 304,
                  teamName: "Oman",
                  teamSName: "OMAN",
                  imageId: 172353,
                },
                venueInfo: {
                  id: 549,
                  ground: "Al Amerat Cricket Ground (Ministry Turf 1)",
                  city: "Al Amerat",
                  timezone: "+04:00",
                  latitude: "23.483316",
                  longitude: "58.4589062",
                },
                currBatTeamId: 304,
                seriesStartDt: "1711929600000",
                seriesEndDt: "1712620800000",
                isTimeAnnounced: true,
                stateTitle: "OMAN Won",
              },
              matchScore: {
                team1Score: {
                  inngs1: {
                    inningsId: 1,
                    runs: 101,
                    wickets: 8,
                    overs: 19.6,
                  },
                },
                team2Score: {
                  inngs1: {
                    inningsId: 2,
                    runs: 104,
                    wickets: 2,
                    overs: 11.1,
                  },
                },
              },
            },
            {
              matchInfo: {
                matchId: 91319,
                seriesId: 7727,
                seriesName: "Namibia tour of Oman, 2024",
                matchDesc: "2nd T20I",
                matchFormat: "T20",
                startDate: "1712053800000",
                endDate: "1712066400000",
                state: "Complete",
                status: "Oman won by 6 runs",
                team1: {
                  teamId: 304,
                  teamName: "Oman",
                  teamSName: "OMAN",
                  imageId: 172353,
                },
                team2: {
                  teamId: 161,
                  teamName: "Namibia",
                  teamSName: "NAM",
                  imageId: 172229,
                },
                venueInfo: {
                  id: 549,
                  ground: "Al Amerat Cricket Ground (Ministry Turf 1)",
                  city: "Al Amerat",
                  timezone: "+04:00",
                  latitude: "23.483316",
                  longitude: "58.4589062",
                },
                currBatTeamId: 304,
                seriesStartDt: "1711929600000",
                seriesEndDt: "1712620800000",
                isTimeAnnounced: true,
                stateTitle: "OMAN Won",
              },
              matchScore: {
                team1Score: {
                  inngs1: {
                    inningsId: 1,
                    runs: 137,
                    wickets: 7,
                    overs: 19.6,
                  },
                },
                team2Score: {
                  inngs1: {
                    inningsId: 2,
                    runs: 131,
                    wickets: 9,
                    overs: 19.6,
                  },
                },
              },
            },
            {
              matchInfo: {
                matchId: 91310,
                seriesId: 7727,
                seriesName: "Namibia tour of Oman, 2024",
                matchDesc: "1st T20I",
                matchFormat: "T20",
                startDate: "1711967400000",
                endDate: "1711980000000",
                state: "Complete",
                status: "Namibia won by 4 wkts",
                team1: {
                  teamId: 304,
                  teamName: "Oman",
                  teamSName: "OMAN",
                  imageId: 172353,
                },
                team2: {
                  teamId: 161,
                  teamName: "Namibia",
                  teamSName: "NAM",
                  imageId: 172229,
                },
                venueInfo: {
                  id: 549,
                  ground: "Al Amerat Cricket Ground (Ministry Turf 1)",
                  city: "Al Amerat",
                  timezone: "+04:00",
                  latitude: "23.483316",
                  longitude: "58.4589062",
                },
                currBatTeamId: 161,
                seriesStartDt: "1711929600000",
                seriesEndDt: "1712620800000",
                isTimeAnnounced: true,
                stateTitle: "NAM Won",
              },
              matchScore: {
                team1Score: {
                  inngs1: {
                    inningsId: 1,
                    runs: 109,
                    wickets: 9,
                    overs: 19.6,
                  },
                },
                team2Score: {
                  inngs1: {
                    inningsId: 2,
                    runs: 114,
                    wickets: 6,
                    overs: 18.4,
                  },
                },
              },
            },
          ],
        },
      },
      {
        seriesAdWrapper: {
          seriesId: 7790,
          seriesName: "Lesotho tour of Eswatini, 2024",
          matches: [
            {
              matchInfo: {
                matchId: 92102,
                seriesId: 7790,
                seriesName: "Lesotho tour of Eswatini, 2024",
                matchDesc: "5th T20I",
                matchFormat: "T20",
                startDate: "1711870200000",
                endDate: "1711882800000",
                state: "Complete",
                status: "Eswatini won by 3 wkts",
                team1: {
                  teamId: 570,
                  teamName: "Lesotho",
                  teamSName: "LSO",
                  imageId: 172622,
                },
                team2: {
                  teamId: 1284,
                  teamName: "Eswatini",
                  teamSName: "SWT",
                  imageId: 248525,
                },
                venueInfo: {
                  id: 1877,
                  ground: "Malkerns Country Club oval",
                  city: "Malkerns",
                  timezone: "+02:00",
                  latitude: "-26.52192",
                  longitude: "31.19320",
                },
                currBatTeamId: 1284,
                seriesStartDt: "1711670400000",
                seriesEndDt: "1712016000000",
                isTimeAnnounced: true,
                stateTitle: "SWT Won",
              },
              matchScore: {
                team1Score: {
                  inngs1: {
                    inningsId: 1,
                    runs: 127,
                    wickets: 9,
                    overs: 20,
                  },
                },
                team2Score: {
                  inngs1: {
                    inningsId: 2,
                    runs: 128,
                    wickets: 7,
                    overs: 18.2,
                  },
                },
              },
            },
            {
              matchInfo: {
                matchId: 92093,
                seriesId: 7790,
                seriesName: "Lesotho tour of Eswatini, 2024",
                matchDesc: "4th T20I",
                matchFormat: "T20",
                startDate: "1711800000000",
                endDate: "1711812600000",
                state: "Complete",
                status: "Eswatini won by 39 runs",
                team1: {
                  teamId: 1284,
                  teamName: "Eswatini",
                  teamSName: "SWT",
                  imageId: 248525,
                },
                team2: {
                  teamId: 570,
                  teamName: "Lesotho",
                  teamSName: "LSO",
                  imageId: 172622,
                },
                venueInfo: {
                  id: 1877,
                  ground: "Malkerns Country Club oval",
                  city: "Malkerns",
                  timezone: "+02:00",
                  latitude: "-26.52192",
                  longitude: "31.19320",
                },
                currBatTeamId: 1284,
                seriesStartDt: "1711670400000",
                seriesEndDt: "1712016000000",
                isTimeAnnounced: true,
                stateTitle: "SWT Won",
              },
              matchScore: {
                team1Score: {
                  inngs1: {
                    inningsId: 1,
                    runs: 153,
                    wickets: 6,
                    overs: 20,
                  },
                },
                team2Score: {
                  inngs1: {
                    inningsId: 2,
                    runs: 114,
                    wickets: 10,
                    overs: 19.5,
                  },
                },
              },
            },
            {
              matchInfo: {
                matchId: 92084,
                seriesId: 7790,
                seriesName: "Lesotho tour of Eswatini, 2024",
                matchDesc: "3rd T20I",
                matchFormat: "T20",
                startDate: "1711783800000",
                endDate: "1711796400000",
                state: "Complete",
                status: "Lesotho won by 8 wkts - 12-over game",
                team1: {
                  teamId: 1284,
                  teamName: "Eswatini",
                  teamSName: "SWT",
                  imageId: 248525,
                },
                team2: {
                  teamId: 570,
                  teamName: "Lesotho",
                  teamSName: "LSO",
                  imageId: 172622,
                },
                venueInfo: {
                  id: 1877,
                  ground: "Malkerns Country Club oval",
                  city: "Malkerns",
                  timezone: "+02:00",
                  latitude: "-26.52192",
                  longitude: "31.19320",
                },
                currBatTeamId: 570,
                seriesStartDt: "1711670400000",
                seriesEndDt: "1712016000000",
                isTimeAnnounced: true,
                stateTitle: "LSO Won",
              },
              matchScore: {
                team1Score: {
                  inngs1: {
                    inningsId: 1,
                    runs: 86,
                    wickets: 8,
                    overs: 12,
                  },
                },
                team2Score: {
                  inngs1: {
                    inningsId: 2,
                    runs: 90,
                    wickets: 2,
                    overs: 10.5,
                  },
                },
              },
            },
          ],
        },
      },
    ],
  }