export const seriesData = [
    {
        seriesAdWrapper: {
          seriesId: 7534,
          seriesName: "Sri Lanka tour of Bangladesh, 2024",
          matches: [
            {
              matchInfo: {
                matchId: 88963,
                seriesId: 7534,
                seriesName: "Sri Lanka tour of Bangladesh, 2024",
                matchDesc: "2nd Test",
                matchFormat: "TEST",
                startDate: "1711771200000",
                endDate: "1712142000000",
                state: "Complete",
                status: "Sri Lanka won by 192 runs",
                team1: {
                  teamId: 5,
                  teamName: "Sri Lanka",
                  teamSName: "SL",
                  imageId: 172119,
                },
                team2: {
                  teamId: 6,
                  teamName: "Bangladesh",
                  teamSName: "BAN",
                  imageId: 172120,
                },
                venueInfo: {
                  id: 93,
                  ground: "Zahur Ahmed Chowdhury Stadium",
                  city: "Chattogram",
                  timezone: "+06:00",
                  latitude: "22.355898",
                  longitude: "91.767766",
                },
                currBatTeamId: 5,
                seriesStartDt: "1709510400000",
                seriesEndDt: "1712275200000",
                isTimeAnnounced: true,
                stateTitle: "SL Won",
              },
              matchScore: {
                team1Score: {
                  inngs1: {
                    inningsId: 1,
                    runs: 531,
                    wickets: 10,
                    overs: 158.6,
                  },
                  inngs2: {
                    slash:"/",
                    flag:"-",
                    inningsId: 3,
                    runs: 157,
                    wickets: 7,
                    overs: 39.6,
                    isDeclared: true,
                  },
                },
                team2Score: {
                  inngs1: {
                    inningsId: 2,
                    runs: 178,
                    wickets: 10,
                    overs: 68.4,
                  },
                  inngs2: {
                    slash:"/",
                    flag:"-",
                    inningsId: 4,
                    runs: 318,
                    wickets: 10,
                    overs: 84.6,
                  },
                },
              },
            },
          ],
        },
      },
      {
        seriesAdWrapper: {
          seriesId: 7727,
          seriesName: "Namibia tour of Oman, 2024",
          matches: [
            {
              matchInfo: {
                matchId: 91337,
                seriesId: 7727,
                seriesName: "Namibia tour of Oman, 2024",
                matchDesc: "4th T20I",
                matchFormat: "T20",
                startDate: "1712313000000",
                endDate: "1712325600000",
                state: "Complete",
                status: "Namibia won by 24 runs",
                team1: {
                  teamId: 161,
                  teamName: "Namibia",
                  teamSName: "NAM",
                  imageId: 172229,
                },
                team2: {
                  teamId: 304,
                  teamName: "Oman",
                  teamSName:"OMN",
                  imageId: 172353,
                },
                venueInfo: {
                  id: 549,
                  ground: "Al Amerat Cricket Ground (Ministry Turf 1)",
                  city: "Al Amerat",
                  timezone: "+04:00",
                  latitude: "23.483316",
                  longitude: "58.4589062",
                },
                currBatTeamId: 161,
                seriesStartDt: "1711929600000",
                seriesEndDt: "1712620800000",
                isTimeAnnounced: true,
                stateTitle: "NAM Won",
              },
              matchScore: {
                team1Score: {
                  inngs1: {
                    inningsId: 1,
                    runs: 164,
                    wickets: 4,
                    overs: 19.6,
                  },
                },
                team2Score: {
                  inngs1: {
                    inningsId: 2,
                    runs: 140,
                    wickets: 9,
                    overs: 19.6,
                  },
                },
              },
            },
            {
              matchInfo: {
                matchId: 91328,
                seriesId: 7727,
                seriesName: "Namibia tour of Oman, 2024",
                matchDesc: "3rd T20I",
                matchFormat: "T20",
                startDate: "1712226600000",
                endDate: "1712239200000",
                state: "Complete",
                status: "Oman won by 8 wkts",
                team1: {
                  teamId: 161,
                  teamName: "Namibia",
                  teamSName: "NAM",
                  imageId: 172229,
                },
                team2: {
                  teamId: 304,
                  teamName: "Oman",
                  teamSName:"OMN",
                  imageId: 172353,
                },
                venueInfo: {
                  id: 549,
                  ground: "Al Amerat Cricket Ground (Ministry Turf 1)",
                  city: "Al Amerat",
                  timezone: "+04:00",
                  latitude: "23.483316",
                  longitude: "58.4589062",
                },
                currBatTeamId: 304,
                seriesStartDt: "1711929600000",
                seriesEndDt: "1712620800000",
                isTimeAnnounced: true,
                stateTitle: "OMAN Won",
              },
              matchScore: {
                team1Score: {
                  inngs1: {
                    inningsId: 1,
                    runs: 101,
                    wickets: 8,
                    overs: 19.6,
                  },
                },
                team2Score: {
                  inngs1: {
                    inningsId: 2,
                    runs: 104,
                    wickets: 2,
                    overs: 11.1,
                  },
                },
              },
            },
            {
              matchInfo: {
                matchId: 91319,
                seriesId: 7727,
                seriesName: "Namibia tour of Oman, 2024",
                matchDesc: "2nd T20I",
                matchFormat: "T20",
                startDate: "1712053800000",
                endDate: "1712066400000",
                state: "Complete",
                status: "Oman won by 6 runs",
                team1: {
                  teamId: 304,
                  teamName: "Oman",
                  teamSName:"OMN",
                  imageId: 172353,
                },
                team2: {
                  teamId: 161,
                  teamName: "Namibia",
                  teamSName: "NAM",
                  imageId: 172229,
                },
                venueInfo: {
                  id: 549,
                  ground: "Al Amerat Cricket Ground (Ministry Turf 1)",
                  city: "Al Amerat",
                  timezone: "+04:00",
                  latitude: "23.483316",
                  longitude: "58.4589062",
                },
                currBatTeamId: 304,
                seriesStartDt: "1711929600000",
                seriesEndDt: "1712620800000",
                isTimeAnnounced: true,
                stateTitle: "OMAN Won",
              },
              matchScore: {
                team1Score: {
                  inngs1: {
                    inningsId: 1,
                    runs: 137,
                    wickets: 7,
                    overs: 19.6,
                  },
                },
                team2Score: {
                  inngs1: {
                    inningsId: 2,
                    runs: 131,
                    wickets: 9,
                    overs: 19.6,
                  },
                },
              },
            },
            {
              matchInfo: {
                matchId: 91310,
                seriesId: 7727,
                seriesName: "Namibia tour of Oman, 2024",
                matchDesc: "1st T20I",
                matchFormat: "T20",
                startDate: "1711967400000",
                endDate: "1711980000000",
                state: "Complete",
                status: "Namibia won by 4 wkts",
                team1: {
                  teamId: 304,
                  teamName: "Oman",
                  teamSName:"OMN",
                  imageId: 172353,
                },
                team2: {
                  teamId: 161,
                  teamName: "Namibia",
                  teamSName: "NAM",
                  imageId: 172229,
                },
                venueInfo: {
                  id: 549,
                  ground: "Al Amerat Cricket Ground (Ministry Turf 1)",
                  city: "Al Amerat",
                  timezone: "+04:00",
                  latitude: "23.483316",
                  longitude: "58.4589062",
                },
                currBatTeamId: 161,
                seriesStartDt: "1711929600000",
                seriesEndDt: "1712620800000",
                isTimeAnnounced: true,
                stateTitle: "NAM Won",
              },
              matchScore: {
                team1Score: {
                  inngs1: {
                    inningsId: 1,
                    runs: 109,
                    wickets: 9,
                    overs: 19.6,
                  },
                },
                team2Score: {
                  inngs1: {
                    inningsId: 2,
                    runs: 114,
                    wickets: 6,
                    overs: 18.4,
                  },
                },
              },
            },
          ],
        },
      },
]